import type { AdmissionGroup } from "./model";
import { getPublishedPublicItems } from "./selectors";

const sourceRoot = "https://www.sncstaguig.com/registration/admission-requirements";
const publicContent = { status: "published", visibility: "public", publishedAt: null } as const;
const common = ["Two photocopies of the PSA birth certificate.", "Three recent, colored 2 × 2 inch ID photos.", "Report card with LRN: one original and two photocopies, signed by the school principal.", "Baptismal certificate, or certificate of dedication for non-Catholic applicants.", "Marriage certificate if the parents are married (optional).", "Two long folders and one long brown envelope."];
const envelope = "Place the documents in a long brown envelope labeled with the applicant’s name in pencil.";
const groups: AdmissionGroup[] = [
  { ...publicContent, id: "returning-student", slug: "returning-student", title: "Returning student", introduction: "For students continuing their studies at SNCS.", requirements: ["Submit the report card to the Admission Office."], notes: ["Contact the Registrar for current enrollment dates and next steps."], sourceUrl: `${sourceRoot}/old-student` },
  { ...publicContent, id: "preschool", slug: "preschool", title: "Preschool", introduction: "For nursery and kindergarten applicants.", requirements: ["Entrance examination for kindergarten applicants.", ...common.map((item) => item.startsWith("Report card") ? "If the applicant has attended school, provide the report card with LRN: one original and two photocopies." : item)], notes: [envelope, "Ask the Registrar to confirm the applicable nursery or kindergarten age requirement."], sourceUrl: `${sourceRoot}/new-student/preschool` },
  { ...publicContent, id: "grade-1", slug: "grade-1", title: "Incoming Grade 1", introduction: "For applicants starting elementary school.", requirements: ["Entrance examination.", ...common], notes: [envelope, "Confirm the applicable age requirement with the Registrar."], sourceUrl: `${sourceRoot}/new-student/incoming-grade-1` },
  { ...publicContent, id: "grade-7", slug: "grade-7", title: "Incoming Grade 7", introduction: "For applicants starting junior high school.", requirements: ["Entrance examination.", ...common, "Certificate of good moral character from the Guidance Counselor or school principal.", "Recommendation form in a sealed envelope."], notes: [envelope, "TLC applicants should first complete the TLC Office’s requirements."], sourceUrl: `${sourceRoot}/new-student/incoming-grade-7` },
  { ...publicContent, id: "senior-high", slug: "senior-high", title: "Senior high school", introduction: "For incoming senior high school applicants.", requirements: ["Entrance examination.", ...common, "Certificate of good moral character and recommendation form in a sealed envelope.", "ESC certificate from the previous school, for ESC grantees only.", "NCAE result for Grade 11, if available or applicable."], notes: [envelope, "Confirm strand-specific grade requirements with the Registrar before applying."], sourceUrl: `${sourceRoot}/new-student/senior-high-school` },
  { ...publicContent, id: "transferee-returnee", slug: "transferee-returnee", title: "Transferee / returnee", introduction: "For applicants transferring to SNCS or returning after studying elsewhere.", requirements: ["Entrance examination.", ...common, "For Grades 4–12: good moral character certificate and a recommendation form in a sealed envelope.", "For ESC grantees entering Grades 8–12: ESC certificate from the previous school."], notes: [envelope, "Contact the Registrar to confirm the checklist for your grade level."], sourceUrl: `${sourceRoot}/new-student/transferee-and-returnee` },
];
export const getPublicAdmissionGroups = () => getPublishedPublicItems(groups);
