import { schoolLevels, type Application } from '../src/lib/enrollment/form.js';

// Column names and enum values from SNCS_Schema_Final.sql. Only these fields
// cross the persistence boundary; processing values are generated by the SQL function.
export function mapEnrollment(data: Application, periodId: string) {
  const optional = (value: string | undefined) => value || null;
  const payment: Record<string, string> = { 'Full Payment/Cash': 'full_cash', Monthly: 'monthly', Quarterly: 'quarterly', 'Semi-Annual': 'semi_annual' };
  return {
    application: {
      period_id: periodId, department: schoolLevels[data.level].department, applicant_type: data.studentStatus.toLowerCase(),
      grade_level: data.gradeLevel, strand: data.level === 'SHS' ? data.strand : null,
      mode_of_payment: payment[data.paymentMode], surname: data.surname, first_name: data.firstName,
      middle_name: optional(data.middleName), birth_date: data.birthday, gender: data.gender.toLowerCase(),
      place_of_birth: data.birthplace, religion: data.religion, complete_address: data.address,
      contact_numbers: data.contact, email: data.email, parent_email: optional(data.parentEmail),
      guardian_messenger: data.messenger, last_school_name: optional(data.previousSchool), last_school_address: optional(data.previousAddress),
    },
    guardians: ['father', 'mother', 'guardian'].filter(relationship => data[`${relationship}FullName`]).map(relationship => ({
      relationship, full_name: data[`${relationship}FullName`],
      occupation: optional(data[`${relationship}Occupation`]), contact_number: optional(data[`${relationship}Contact`]),
    })),
  };
}
